clone_folder: C:\M

environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: alexpux
    BINTRAY_REPOSITORY: msys2
    PACMAN_REPOSITORY_NAME: ci.mingw
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
    matrix:
        - MINGW_INSTALLS: mingw32
        - MINGW_INSTALLS: mingw64

matrix:
    fast_finish: true

build_script:
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

test: off

artifacts:
    - path: artifacts\*

deploy:
    - provider: BinTray
      username: $(BINTRAY_ACCOUNT)
      subject: $(BINTRAY_ACCOUNT)
      repo: $(BINTRAY_REPOSITORY)
      package: $(PACMAN_REPOSITORY_NAME)
      version: latest
      publish: true
      override: true
      api_key:
          secure: B2XBLbsX8EQOpWyyaHskipMoF2+Tbt6hc/afbVm82f01CBKruspjwhee4K4C7/xf
