name: Environment request
description: Request that a package be built for a specific environment
title: Build [package name] for [environment]
labels: [package-request]
body:
  - type: input
    attributes:
      label: Package name
    validations:
      required: true
  - type: dropdown
    attributes:
      label: For which environment do you need the package?
      options:
        - MINGW64
        - MINGW32
        - UCRT64
        - CLANG64
        - CLANG32
        - CLANGARM64
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide a brief description why you need this package in the selected environment
    validations:
      required: true
  - type: input
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!
