# see src/bootstrap/defaults/
profile = "dist"

# see src/bootstrap/src/utils/change_tracker.rs
change-id = 129295

[build]
#cargo = "$MINGW_PREFIX/bin/cargo.exe"
#rustc = "$MINGW_PREFIX/bin/rustc.exe"
#rustfmt = "$MINGW_PREFIX/bin/rustfmt.exe"
build = "$OSTYPE"
host = ["$OSTYPE"]
target = [
  "$OSTYPE",
]
python = "$MINGW_PREFIX/bin/python.exe"
locked-deps = true
vendor = true
tools = [
  "cargo",
  "clippy",
  "rustdoc",
  "rustfmt",
  "rust-analyzer-proc-macro-srv",
  "analysis",
  "src",
]
sanitizers = true
profiler = true

# Generating docs fails with the wasm32-* targets
docs = false

[install]
prefix = "$INSTALL_PREFIX"
sysconfdir = "etc"

[rust]
#debug = true
codegen-units-std = 1
#debuginfo-level-std = 2
parallel-compiler = false
channel = "stable"
description = "Rev$PKGREL, Built by MSYS2 project"
rpath = false
frame-pointers = true
lld = false
codegen-tests = false
deny-warnings = false
backtrace-on-ice = true
# FIXME: CFG can be enabled only for MSVC targets as for https://github.com/rust-lang/rust/pull/74103
# control-flow-guard = true

[dist]
compression-formats = ["gz"]
include-mingw-linker = false

[target.$OSTYPE]
llvm-config = "$MINGW_PREFIX/bin/llvm-config.exe"

[target.wasm32-unknown-unknown]
sanitizers = false
profiler = false

[target.wasm32-wasip1]
sanitizers = false
profiler = false
wasi-root = "$MINGW_PREFIX/share/wasi-sysroot"

[target.wasm32-wasip1-threads]
sanitizers = false
profiler = false
wasi-root = "$MINGW_PREFIX/share/wasi-sysroot"

[target.wasm32-wasip2]
sanitizers = false
profiler = false
wasi-root = "$MINGW_PREFIX/share/wasi-sysroot"
